# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches: [main, master]
    paths-ignore:
      - 'pkgdown/**'
      - '.github/workflows/pkgdown.yaml'
  pull_request:
    branches: [main, master]
    paths-ignore:
      - 'pkgdown/**'
      - '.github/workflows/pkgdown.yaml'

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }}) [Pandoc ${{ matrix.config.pandoc }}]

    strategy:
      fail-fast: false
      matrix:
        config:
          # testing R release with last shipped pandoc version in RStudio IDE and new pandoc
          - {os: windows-latest,  pandoc: '2.17.1.1', r: 'release'}
          - {os: macOS-latest,    pandoc: '2.17.1.1', r: 'release'}
          - {os: ubuntu-latest,   pandoc: '2.17.1.1', r: 'release'}
          - {os: ubuntu-latest,   pandoc: 'devel',    r: 'release'}
          # # testing older pandoc versions
          - {os: ubuntu-latest,   pandoc: '2.16.1',   r: 'release'}
          - {os: ubuntu-latest,   pandoc: '2.14.2',   r: 'release'}
          - {os: ubuntu-latest,   pandoc: '2.11.4',   r: 'release'}
          # # testing other R versions
          - {os: ubuntu-latest,   pandoc: '2.14.2',   r: 'oldrel'}
          - {os: ubuntu-latest,   pandoc: '2.14.2',   r: 'devel', http-user-agent: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v2
        if: matrix.config.pandoc != 'devel'
        with:
          pandoc-version: ${{ matrix.config.pandoc }}

      - uses: cderv/actions/setup-pandoc-nightly@nightly-pandoc
        if: matrix.config.pandoc == 'devel'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - name: Install extra dependencies
        uses: ./.github/actions/install-ghostscript

      - uses: r-lib/actions/check-r-package@v2

      - name: Test coverage
        if: success() && runner.os == 'Linux' && matrix.config.r == 'release' && matrix.config.pandoc == '2.7.3'
        run: |
          pak::pkg_install('covr')
          covr::codecov()
        shell: Rscript {0}
