# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  workflow_dispatch:
  workflow_run:
      workflows: ["R-CMD-check"]
      types:
        - completed

name: Build Examples

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    if: github.event.name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success'
    name: 'ubuntu-latest (R release) [Pandoc 2.14.2]'

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: 2.14.2

      - uses: r-lib/actions/setup-r-dependencies@v1

      - name: Build examples
        run: Rscript tools/website.R
        shell: bash
